cluster.name: "es-docker-cluster"
network.host: 0.0.0.0
xpack.security.enabled: true
xpack:
  security:
    authc:
      realms:
        ldap:
          ldap1:
            order: 0
            url: "ldaps://my.domain.example.com"
            bind_dn: "cn=mycontaineradmin,cn=users,dc=my,dc=domain,dc=example,dc=com"
            user_search:
              base_dn: "dc=my,dc=domain,dc=example,dc=com"
              filter: "(&(objectClass=user)(memberOf=cn=My-Group-Staff,ou=My Groups,dc=my,dc=domain,dc=example,dc=com))"

